"""add unique constraint to document chunks

Revision ID: b4878d197da1
Revises: f1914f126131
Create Date: 2026-08-25 09:35:17.062516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4878d197da1'
down_revision: Union[str, Sequence[str], None] = 'f1914f126131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_chunk_source_index', 'document_chunks', ['source_id', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_chunk_source_index', 'document_chunks', type_='unique')
    # ### end Alembic commands ###
